name: "Security Extended"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run OSSAR
        uses: github/ossar-action@v1
        continue-on-error: true
        
      - name: Run Retire.js
        uses: RetireJS/retire@v3
        continue-on-error: true
        with:
          node: true

  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Super-Linter
        uses: github/super-linter@v5
        env:
          VALIDATE_JAVASCRIPT_ES: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_INCLUDE: .*\.(js|jsx|ts|tsx)$
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
          VALIDATE_ALL_CODEBASE: false
        continue-on-error: true

  bundle-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Analyze JavaScript Files
        run: |
          find . -type f -name "*.js" -exec wc -l {} \;
          find . -type f -name "*.js" -exec du -h {} \;
